language: ruby
bundler_args: --without debug extra
rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - jruby-19mode
  - jruby-head
  - rbx
notifications:
  email:
    recipients:
      - sylvester@keil.or.at
    on_success: change
    on_failure: always
