language: ruby
bundler_args: --without debug extra
rvm:
  - 2.0.0
  - 1.9.2
  - 1.9.3
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
  - rbx-20mode
  - 1.8.7
  - ree
notifications:
  email:
    recipients:
      - sylvester@keil.or.at
    on_success: change
    on_failure: always
matrix:
  allow_failures:
	  - rvm: jruby-19mode
    - rvm: rbx-19mode